version: '3.8'

services:
  web:
    build: .
    container_name: loja_online_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD= admin123
      - MYSQL_DATABASE= loja_online
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=acessoBanco

  db:
    image: mysql:5.7
    container_name: loja_online_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=loja_online
      - MYSQL_USER=admin  
      - MYSQL_PASSWORD=acessoBanco

volumes:
  db_data:




