version: '3.8'

services:
  web:
    build: .
    container_name: loja_online_web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USERNAME=admin
      - DB_PASSWORD=acessoBanco
      - DB_DATABASE=loja_online
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: loja_online_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=loja_online
      - MYSQL_USER=admin  
      - MYSQL_PASSWORD=acessoBanco
    restart: unless-stopped

volumes:
  db_data:




